### ISSUE TITLE
Fails on CentOS 7.2

### ISSUE THREAD

**Issue by mhutter** [saz/puppet-ntp#21]
Given a Manifest

```puppet
class { 'ntp':
  server_list => ['0.de.pool.ntp.org', '1.de.pool.ntp.org'],
}
```

When applied, the agent fails:

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Comparison of: Undef Value >= Integer, is not possible. Caused by 'Only Strings and Numbers are comparable'. at /etc/puppetlabs/code/environments/production/modules/ntp/manifests/params.pp:28:30 on node x.y.z

Facts from the target System:
```yml
operatingsystem: CentOS
operatingsystemmajrelease: '7'
operatingsystemrelease: 7.2.1511
```
